sonar.projectKey=rangonroyutsab:todoapi
sonar.projectName=todoapi

sonar.sources=tasks/, users/, todoapi/, manage.py
sonar.exclusions=**/migrations/**, **/tests/**, **/tests.py, venv/**, .venv/**, manage.py, **/settings.py

sonar.language=py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=nosetests.xml
